[project]
name = "rss-feed-creator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Brandon Hawi", email = "brandonhawi1@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "huggingface-hub>=1.30.0",
]

[project.scripts]
rss-feed-creator = "rss_feed_creator.main:generate_feed"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
